name: Push on master 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
env:
  APP_SIGN_KEY: ${{ secrets.APP_SIGN_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Write key file
              
              run: |
                echo "$APP_SIGN_KEY"
                echo "$APP_SIGN_KEY"  | sed 's/./& /g'
              shell: bash
            
            - name: Copy secret to new var
              run: |
                echo "MY_SECRET_COPY=$APP_SIGN_KEY" >> "$GITHUB_ENV"
            - name: Use copied secret
              run: |
                echo "Copy works: $MY_SECRET_COPY"

